[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://bvtupcwaounomfhtryxm.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2dHVwY3dhb3Vub21maHRyeXhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNzkxOTUsImV4cCI6MjA1ODc1NTE5NX0.Lcb6zvb5oGiKa0W9GpZkfLH4vVMbP6G_-mtR5mQoaUU"
  DEEPSEEK_API_KEY = "sk-2bfbb38e4faa4fa5b6eb4ae624b3a6d3"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2dHVwY3dhb3Vub21maHRyeXhtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MzE3OTE5NSwiZXhwIjoyMDU4NzU1MTk1fQ.Mf7NA_4I8F1XwD-tYc6lQOLGzSoHb0nSLDspYOkVBNs"
  NEXT_PUBLIC_TELEGRAM_BOT_NAME = "vimct_bot"
  TELEGRAM_BOT_TOKEN = "8042766421:AAGyOqwfmNp3zDk55yX4tMRZkBkfiSiLPbY"
  PASSWORD_SECRET = "TelegramOverwatchSecretKey2024"
  BYPASS_TELEGRAM_AUTH = "true"
  NEXT_PUBLIC_DEFAULT_BANNER = "/images/overwatch_bg_2.jpg"
  NEXT_PUBLIC_APP_URL = "ms-ci-phongcach-clone-ovw.netlify.app"
  NEXT_PUBLIC_USE_DIRECT_API_KEYS = "true"
  NEXT_PUBLIC_USE_FALLBACK_RESPONSES = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs" 